// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProgram returns the embedded CollectionSpec for program.
func loadProgram() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProgramBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load program: %w", err)
	}

	return spec, err
}

// loadProgramObjects loads program and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*programObjects
//	*programPrograms
//	*programMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProgramObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProgram()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// programSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programSpecs struct {
	programProgramSpecs
	programMapSpecs
	programVariableSpecs
}

// programProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programProgramSpecs struct {
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve  *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceOpenat  *ebpf.ProgramSpec `ebpf:"trace_openat"`
}

// programMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programMapSpecs struct {
	Events    *ebpf.MapSpec `ebpf:"events"`
	TargetPid *ebpf.MapSpec `ebpf:"target_pid"`
}

// programVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programVariableSpecs struct {
}

// programObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programObjects struct {
	programPrograms
	programMaps
	programVariables
}

func (o *programObjects) Close() error {
	return _ProgramClose(
		&o.programPrograms,
		&o.programMaps,
	)
}

// programMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programMaps struct {
	Events    *ebpf.Map `ebpf:"events"`
	TargetPid *ebpf.Map `ebpf:"target_pid"`
}

func (m *programMaps) Close() error {
	return _ProgramClose(
		m.Events,
		m.TargetPid,
	)
}

// programVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programVariables struct {
}

// programPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programPrograms struct {
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve  *ebpf.Program `ebpf:"trace_execve"`
	TraceOpenat  *ebpf.Program `ebpf:"trace_openat"`
}

func (p *programPrograms) Close() error {
	return _ProgramClose(
		p.TraceConnect,
		p.TraceExecve,
		p.TraceOpenat,
	)
}

func _ProgramClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed program_bpfel.o
var _ProgramBytes []byte
