// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type programIpv6Address struct {
	_     structs.HostLayout
	Words [4]uint32
}

// loadProgram returns the embedded CollectionSpec for program.
func loadProgram() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProgramBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load program: %w", err)
	}

	return spec, err
}

// loadProgramObjects loads program and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*programObjects
//	*programPrograms
//	*programMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProgramObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProgram()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// programSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programSpecs struct {
	programProgramSpecs
	programMapSpecs
	programVariableSpecs
}

// programProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programProgramSpecs struct {
	EnforceConnect4  *ebpf.ProgramSpec `ebpf:"enforce_connect4"`
	EnforceConnect6  *ebpf.ProgramSpec `ebpf:"enforce_connect6"`
	EnforceSendmsg4  *ebpf.ProgramSpec `ebpf:"enforce_sendmsg4"`
	EnforceSendmsg6  *ebpf.ProgramSpec `ebpf:"enforce_sendmsg6"`
	TraceConnect     *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceConnectExit *ebpf.ProgramSpec `ebpf:"trace_connect_exit"`
	TraceExecve      *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceOpenat      *ebpf.ProgramSpec `ebpf:"trace_openat"`
}

// programMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programMapSpecs struct {
	AllowedIpv4  *ebpf.MapSpec `ebpf:"allowed_ipv4"`
	AllowedIpv6  *ebpf.MapSpec `ebpf:"allowed_ipv6"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	TargetCgroup *ebpf.MapSpec `ebpf:"target_cgroup"`
}

// programVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programVariableSpecs struct {
}

// programObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programObjects struct {
	programPrograms
	programMaps
	programVariables
}

func (o *programObjects) Close() error {
	return _ProgramClose(
		&o.programPrograms,
		&o.programMaps,
	)
}

// programMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programMaps struct {
	AllowedIpv4  *ebpf.Map `ebpf:"allowed_ipv4"`
	AllowedIpv6  *ebpf.Map `ebpf:"allowed_ipv6"`
	Events       *ebpf.Map `ebpf:"events"`
	TargetCgroup *ebpf.Map `ebpf:"target_cgroup"`
}

func (m *programMaps) Close() error {
	return _ProgramClose(
		m.AllowedIpv4,
		m.AllowedIpv6,
		m.Events,
		m.TargetCgroup,
	)
}

// programVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programVariables struct {
}

// programPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programPrograms struct {
	EnforceConnect4  *ebpf.Program `ebpf:"enforce_connect4"`
	EnforceConnect6  *ebpf.Program `ebpf:"enforce_connect6"`
	EnforceSendmsg4  *ebpf.Program `ebpf:"enforce_sendmsg4"`
	EnforceSendmsg6  *ebpf.Program `ebpf:"enforce_sendmsg6"`
	TraceConnect     *ebpf.Program `ebpf:"trace_connect"`
	TraceConnectExit *ebpf.Program `ebpf:"trace_connect_exit"`
	TraceExecve      *ebpf.Program `ebpf:"trace_execve"`
	TraceOpenat      *ebpf.Program `ebpf:"trace_openat"`
}

func (p *programPrograms) Close() error {
	return _ProgramClose(
		p.EnforceConnect4,
		p.EnforceConnect6,
		p.EnforceSendmsg4,
		p.EnforceSendmsg6,
		p.TraceConnect,
		p.TraceConnectExit,
		p.TraceExecve,
		p.TraceOpenat,
	)
}

func _ProgramClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed program_bpfel.o
var _ProgramBytes []byte
